idf_component_register(
SRCS
    "utils.c"
    "mining.c"
    "notify_validate.c"
    "stratum_api.c"
    "stratum_socket.c"
    "coinbase_decoder.c"
    "segwit_addr.c"
    "base58.c"

INCLUDE_DIRS
    "include"

REQUIRES
    "mbedtls"
    "app_update"
    "esp_timer"
    "tcp_transport"
    "esp_netif"
    "esp_psram"
)
